### PR TITLE
Add byte[] converter to support Javascript for Outlook

### PR DESCRIPTION
**Pull request by ConnorMcMahon**

### CODE REVIEW

**Comment by adamdaum** [comment]
What's the process to get this merged and released?  Very confused about this?  This pull request came about as the result of a ticket I opened with Azure support a month ago.  If I'm understanding this correctly, the outlook binding with Javascript in Azure functions doesn't work at all.  Like AT ALL.  Am I understanding that correctly? .. That seems significant to me, as it's documented with examples on docs.microsoft.com, and there's an option to select it in the bindings in the function editor on the portal, etc.  Shouldn't it work, and shouldn't there be more urgency to fix it?  Am I missing something?

 [microsoft docs](https://docs.microsoft.com/en-us/azure/azure-functions/functions-bindings-microsoft-graph#outlook-output---javascript-example)

**Comment by ConnorMcMahon** [comment]
@adamdaum You are right that there should be more urgency in fixing this broken scenario. I will ensure that an updated dll of the extension gets published in the next few days. 

Unfortunately, there are gaps in the usage story of this extension that have prevented us from pouring more resources into it. For one, there isn't a good way to update the extension version in the portal, so the portal is pinned to an early version. Also, there isn't a good local development story for this extension, since EasyAuth doesn't work with the Azure Functions CLI. Finally, we are renovating how the underlying token binding works to make it more robust and secure.

We have been working on addressing all of these issues, and once they are in place, the overall experience for working with the Microsoft Graph binding should be much better. We will then have more resources to iron out bugs and add features to this binding.

I apologize for how slow development has been on this binding, but expect it to see some love in the future!

**Comment by adamdaum** [comment]
@ConnorMcMahon, thanks for the explanation. Glad to hear there’s more love in store, cuz I think Azure functions are a rad product and plan on using them a lot more in the future and one of the most attractive features Is being able to easily integrate with the Graph Api resources.

**Comment by cobase2010** [comment]
I am still hitting this issue. Has this fix been released yet?

**Comment by gxs54** [comment]
I am having the same problem Any update on when this will be fixed?

**Comment by ahuggins-nhs** [comment]
@ConnorMcMahon Any word on when the portal version will be synced up with the fix for JavaScript? I'm heavily invested in Node for Azure Function development, and right now it looks like I cannot use Graph at all. I'm seriously considering developing a C# function just so that I can call Graph from a JavaScript function successfully. I understand that this is still in beta, just looking to see when this will get more love.

**Pull request merged**
